services:
  postgres:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    ports:
      - 5433:5432
    volumes:
      - ./data/db/postgres/data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass "hOW32#$@41u31Aq4"
    ports:
      - "6379:6379"
    volumes:
      - ./data/db/redis/redis-data:/var/lib/redis
      - ./data/db/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
